module.exports = {
    catchError: require('rxjs/internal/operators/catchError').catchError,
    concat: require('rxjs/internal/observable/concat').concat,
    delay: require('rxjs/internal/operators/delay').delay,
    empty: require('rxjs/internal/observable/empty').empty,
    expand: require('rxjs/internal/operators/expand').expand,
    filter: require('rxjs/internal/operators/filter').filter,
    from: require('rxjs/internal/observable/from').from,
    last: require('rxjs/internal/operators/last').last,
    map: require('rxjs/internal/operators/map').map,
    mergeMap: require('rxjs/internal/operators/mergeMap').mergeMap,
    Observable: require('rxjs/internal/Observable').Observable,
    of: require('rxjs/internal/observable/of').of,
    pluck: require('rxjs/internal/operators/pluck').pluck,
    range: require('rxjs/internal/observable/range').range,
    reduce: require('rxjs/internal/operators/reduce').reduce,
    retryWhen: require('rxjs/internal/operators/retryWhen').retryWhen,
    take: require('rxjs/internal/operators/take').take,
    tap: require('rxjs/internal/operators/tap').tap,
    throwError: require('rxjs/internal/observable/throwError').throwError,
    toArray: require('rxjs/internal/operators/toArray').toArray
};